# fly.toml app configuration file generated for damp-haze-3050 on 2023-10-01T20:39:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-haze-3050"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
