package echoboard.echoboard.echo;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import echoboard.echoboard.configuration.InstantConverter;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;

@Getter
@Setter
@ToString
@DynamoDBTable(tableName ="CommentBoard")
public class Comment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private String comment;

    @DynamoDBAttribute
    private Long upvote;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = InstantConverter.class)
    private Instant created;

    public Comment(String author, String comment, String echoBoardId) {
        this.author = author;
        this.comment = comment;
        this.upvote = 0L;
        this.created = Instant.now();
    }
}
