package echoboard.echoboard.echo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;
import java.time.LocalDateTime;

@Getter
@Setter
@ToString
@DynamoDBTable(tableName ="CommentBoard")
public class Comment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private String comment;

    @DynamoDBAttribute
    private Long upvote;

    @DynamoDBAttribute
    private Instant created;

    public Comment(String author, String comment) {
        this.author = author;
        this.comment = comment;
        this.upvote = 0L;
        this.created = Instant.now();
    }
}
