package echoboard.echoboard.echo;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import echoboard.echoboard.configuration.InstantConverter;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@ToString
@DynamoDBTable(tableName = "EchoBoardDevelopment")
public class Comment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private String comment;

    @DynamoDBAttribute
    private Long upvote;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = InstantConverter.class)
    private Instant created;

    public Comment(String author, String comment) {
        this.id = UUID.randomUUID().toString();
        this.author = author;
        this.comment = comment;
        this.upvote = 0L;
        this.created = Instant.now();
    }

    public Comment() {
        this.id = UUID.randomUUID().toString();
        this.upvote = 0L;
        this.created = Instant.now();
    }

}
