package echoboard.echoboard.echo;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.ToString;

import java.time.LocalDateTime;

@Getter
@ToString
@DynamoDBTable(tableName = "EchoBoard")
public class Echo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Long id;

    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String content;
    @DynamoDBAttribute
    private String author;
    @DynamoDBAttribute
    private int upvotes;
    @DynamoDBAttribute
    private int downvotes;
    @DynamoDBAttribute
    private LocalDateTime created;

    public Echo(String title, String content, String author) {
        this.title = title;
        this.content = content;
        this.author = author;
        this.upvotes = 0;
        this.downvotes = 0;
    }

    protected Echo() {
    }

    @PrePersist
    private void onCreate() {
        this.created = LocalDateTime.now();
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public void setUpvotes(int upvotes) {
        this.upvotes = upvotes;
    }

    public void setDownvotes(int downvotes) {
        this.downvotes = downvotes;
    }

}

