package echoboard.echoboard.echo;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import echoboard.echoboard.configuration.InstantConverter;
import lombok.Getter;
import lombok.ToString;

import java.time.Instant;

@Getter
@ToString
@DynamoDBTable(tableName = "EchoBoardDevelopment")
public class EchoBoard {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String content;
    @DynamoDBAttribute
    private String author;
    @DynamoDBAttribute
    private Long upvote;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = InstantConverter.class)
    private Instant created;

    public EchoBoard(String title, String content, String author) {
        this.title = title;
        this.content = content;
        this.author = author;
        this.upvote = 0L;
        this.created = Instant.now();
    }

    public EchoBoard() {
        created = Instant.now();
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public void setUpvote(Long upvote) {
        this.upvote = upvote;
    }

    public void setCreated(Instant created) {
        this.created = created;
    }

}

