version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
#      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
