version: '3'
services:
  my-java-app:
    image: amazoncorretto:17.0.8-alpine3.18
    container_name: echoboard-container
    ports:
      - "8080:8080"
    volumes:
      - ./target/echoboard-0.0.1-SNAPSHOT.jar:/echoboard-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/echoboard-0.0.1-SNAPSHOT.jar"]
