server:
  forward-headers-strategy: none
  port: 8080
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
        multiTenancy: SCHEMA
logging:
  level:
    org:
#      springframework: info
#        security: TRACE
#        messaging: DEBUG
#        http: DEBUG
      hibernate:
        SQL: TRACE
        type:
        descriptor:
          sql:
          BasicBinder: TRACE
website:
  base-url:
    backend: http://localhost:8080/
    frontend: http://localhost:3000/
