server:
  address: 0.0.0.0
  port: 8080
spring:
  config:
    import: optional:secrets.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
  datasource:
    url: ${DATABASE_URL}   # JDBC URL for PostgreSQL
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop        # Automatically create/update database schema
    show-sql: true    # Show SQL queries in logs
  profiles:
    default: deploy

