
spring:
  config:
    import: optional:secrets.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
amazon:
  aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  dynamodb:
    region: ${AWS_REGION}
    endpoint: ${AWS_ENDPOINT}