server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        same-site: none
spring:
  config:
    import: optional:secrets.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  profiles:
    default: deploy
frontend-details:
#    base-url: https://app.echoboard.site/
  base-url: http://localhost:3000/
backend-details:
#    base-url: https://api.echoboard.site/
  base-url: http://localhost:8080/
logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        http : DEBUG
      hibernate:
        sql: DEBUG