spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: ${DATABASE_URL_DEV1}
    username: ${DATABASE_USER1}
    password: ${DATABASE_PASSWORD1}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: off
    properties:
      hibernate:
        multiTenancy: SCHEMA
        tenant_identifier_resolver: se.salt.echoboard.multitenancy.data.hibernate.TenantIdentifierResolver
backend-details:
 base-url: http://localhost:8080/
frontend-details:
  base-url: http://localhost:3000/
logging:
  level:
    org:
#      springframework: info
#        security: TRACE
#        messaging: DEBUG
#        http: DEBUG
      hibernate:
        SQL: TRACE
        type:
        descriptor:
          sql:
          BasicBinder: TRACE