server:
  forward-headers-strategy: native
  port: 8080
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: ${DATABASE_URL_DEV1}
    username: ${DATABASE_USER1}
    password: ${DATABASE_PASSWORD1}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
backend-details:
 base-url: http://localhost:8080/
frontend-details:
  base-url: http://localhost:3000/
logging:
  level:
    org:
      springframework:
#        security: TRACE
        messaging: INFO
#        http: DEBUG
      hibernate:
        sql: TRACE
#        type:
#          descriptor:
#            sql:
#              BasicBinder:
#                TRACE