server:
  forward-headers-strategy: native
  port: 8080
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always

frontend-details:
  base-url: http://localhost:3000
logging:
  level:
    org:
      springframework:
        security: TRACE
#      hibernate:
#        sql: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder:
#                TRACE