server:
  forward-headers-strategy: native
  port: 8080
spring:
  config:
    import: optional:secrets.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
  datasource:
    url: ${DATABASE_URL_DEV}   # JDBC URL for PostgreSQL
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update      # Automatically create/update database schema
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always

frontend-details:
  base-url: http://localhost:3000
logging:
  level:
    org:
      springframework:
        security: TRACE
#      hibernate:
#        sql: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder:
#                TRACE