server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        same-site: none
spring:
  config:
    import: optional:secrets.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  profiles:
    default: deploy
logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        http : DEBUG
        security: DEBUG
      hibernate:
        sql: DEBUG
multitenancy:
  http:
    header-name: X-TenantId
website:
  base-url:
#    backend: http://localhost:8080/
    backend: https://api.echoboard.site/
#    frontend: http://localhost:3000/
    frontend: https://app.echoboard.site/
