name: Fly Auth

on:
  push:
    branches:
      - main
      - 91-setup-github-workflow-for-fly-cicd
    paths:
      - 'src/**'
      - '.github/**'
      - 'Dockerfile'

jobs:
  user-check:
    name: Who am I
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth whoami
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}